version: '3'

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx/
    restart: on-failure
    ports:
      - "443:443"
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - default
  wordpress:
    container_name: wordpress
    depends_on: 
      - mariadb
    build: requirements/wordpress/
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - default
    ports:
      - "9000"
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    restart: on-failure
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - default
    ports:
      - "3306"

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: '/home/smagdela/data/wordpress'
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none 
      o: bind
      device: '/home/smagdela/data/mariadb'

networks:
  default:
    driver: bridge
