version: '3'

services:
        nginx:
                depends_on:
                        - wordpress
                build: requirements/nginx/
                restart: on-failure
                ports:
                        - "443:443"
                env_file: .env
        wordpress:
                depends_on: 
                        - mariadb
                build: requirements/wordpress/
                restart: on-failure
                env_file: .env
                expose:
                        - "9000"
                links:
                        - mariadb
        mariadb:
                build: requirements/mariadb/
                restart: on-failure
                env_file: .env
                expose:
                        - "3306"

