version: '3'

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "443:443"
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - backend

  wordpress:
    container_name: wordpress
    depends_on: 
      - mariadb
    build:
      context: ./requirements/wordpress/
      dockerfile: ./Dockerfile
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - backend

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: ./Dockerfile
    restart: on-failure
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: '/home/smagdela/data/wordpress'
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none 
      o: bind
      device: '/home/smagdela/data/mariadb'

networks:
  backend:
    name: backend
    driver: bridge
