version: '3'

services:
        nginx:
                container_name: nginx
                depends_on:
                        - wordpress
                build: requirements/nginx/
                restart: on-failure
                ports:
                        - "443:443"
                env_file: .env
                volumes:
                  - wordpress_data:/var/www/html
                networks:
                  - default
        wordpress:
                container_name: wordpress
                depends_on: 
                        - mariadb
                build: requirements/wordpress/
                restart: on-failure
                env_file: .env
                links:
                        - mariadb
                volumes:
                  - wordpress_data:/var/www/html
                networks:
                  - default
        mariadb:
                container_name: mariadb
                build: requirements/mariadb/
                restart: on-failure
                env_file: .env
                networks:
                  - default

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/vbachele/data/wordpress
      o: bind
# Add mariadb volume

networks:
  default:
    driver: bridge
# Check netoworks